additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: $BASE_DOMAIN  # your base domain
compute:
- architecture: amd64
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      type: m6i.4xlarge
      rootVolume:
        size: 100
        iops: 4000
        type: io1
      zones:
      - $AWS_ZONE  # your AWS zone
  replicas: 3
metadata:
  creationTimestamp: null
  name: $CLUSTER_NAME  # your cluster name
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/19
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: $AWS_REGION  # your AWS region
    userTags:
      adminContact: sshnaidm
      Policy: skip
      propagateUserTags: true
publish: External
pullSecret: '$PULL_SECRET'
sshKey: |
  $PUBLIC_SSH_KEY
