apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: "repo-5g-devops-ci-infra-12345"
  namespace: openshift-gitops
data:
  insecure: dHJ1ZQ==
  type: Z2l0Cg==
  url: "$GIT_REPO_URL"
