apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-clusters
  namespace: openshift-gitops
spec:
  destination:
    namespace: aws-sub
    server: https://kubernetes.default.svc
  # ignoreDifferences:
  # - group: cluster.open-cluster-management.io
  #   kind: ManagedCluster
  #   managedFieldsManagers:
  #   - controller
  project: aws-cluster
  source:
    path: aws
    repoURL:
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
