apiVersion: v1
data:
  password: $USER_PASSWORD
  username: $USER_NAME
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: ${APP_NAME}
    environment.metal3.io: baremetal
  name: ${CLUSTER_NAME}-bmh-secret
  namespace: ${CLUSTER_NAME}
type: Opaque
---
apiVersion: v1
data:
  .dockerconfigjson: $PULL_SECRET
kind: Secret
metadata:
  labels:
    agent-install.openshift.io/watch: "true"
    app.kubernetes.io/instance: ${APP_NAME}
  name: assisted-deployment-pull-secret
  namespace: ${CLUSTER_NAME}
type: kubernetes.io/dockerconfigjson
