additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: telco5g-ci.devcluster.openshift.com  # your base domain
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      type: m6i.4xlarge
  replicas: 1
metadata:
  creationTimestamp: null
  name: my-ocp-cluster  # your cluster name
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/19
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
publish: External
pullSecret: '<your pull secret>'
sshKey: |
  ssh-rsa AAAAB3N...... - you public key
