---
apiVersion: v1
kind: Namespace
metadata:
  name: '${CLUSTER_NAME}'
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CLUSTER_NAME}-pull-secret
  namespace: '${CLUSTER_NAME}'
stringData:
  .dockerconfigjson: |-
    ${PULL_SECRET}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CLUSTER_NAME}-install-config
  namespace: '${CLUSTER_NAME}'
type: Opaque
data:
  # Base64 encoding of install-config yaml
  install-config.yaml: ${INSTALL_CONFIG}
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CLUSTER_NAME}-ssh-private-key
  namespace: '${CLUSTER_NAME}'
stringData:
  ssh-privatekey: |-
${SSH_PRIVATE_KEY}
type: Opaque
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${CLUSTER_NAME}-aws-creds
  namespace: '${CLUSTER_NAME}'
stringData:
  aws_access_key_id: ${AWS_ACCESS_KEY}
  aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
---
